name: Upload Python Package

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write  # 允许 OIDC 认证

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Clean previous builds
        run: |
          rm -rf dist/ build/ *.egg-info/

      - name: Build release distributions
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine
          python -m build
          python -m twine check dist/*

      - name: Display build contents
        run: |
          ls -la dist/

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build

    environment:
      name: pypi
      url: https://pypi.org/project/pysp-xcw/

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Display package files
        run: |
          ls -la dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          verbose: true
          print-hash: true